//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zenergy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @event()
        {
            this.user = new HashSet<user>();
        }
    
        public int eventId { get; set; }
        public int roomId { get; set; }
        public int activityId { get; set; }
        public string eventName { get; set; }
        public Nullable<decimal> eventPrice { get; set; }
        public Nullable<decimal> eventDurationHours { get; set; }
        public Nullable<int> eventMaxPeople { get; set; }
        public string eventDescription { get; set; }
        public Nullable<System.TimeSpan> timeBegin { get; set; }
    
        public virtual activity activity { get; set; }
        public virtual ponctualEvent ponctualEvent { get; set; }
        public virtual regularEvent regularEvent { get; set; }
        public virtual room room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user { get; set; }
    }
}
