//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zenergy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regularEvent
    {
        public int eventId { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public string dateDay { get; set; }
    
        public virtual @event @event { get; set; }
    }
}
