//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zenergy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZenergyContext : DbContext
    {
        public ZenergyContext()
            : base("name=ZenergyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accessory> accessory { get; set; }
        public virtual DbSet<activity> activity { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<CartContent> CartContent { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<contributor> contributor { get; set; }
        public virtual DbSet<@event> @event { get; set; }
        public virtual DbSet<manager> manager { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<notification> notification { get; set; }
        public virtual DbSet<ponctualEvent> ponctualEvent { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<purchase> purchase { get; set; }
        public virtual DbSet<purchaseContent> purchaseContent { get; set; }
        public virtual DbSet<regularEvent> regularEvent { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<roomContent> roomContent { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
